
export  const emailData = [
  {
      id:1,
    subject: "Help strengthen the security of your Google Account",
    sender: "<no-reply@accounts.google.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:
      "Some apps or services you allowed to access your Google Account have not been verified by Google. Since they have extensive access to your personal information, you should remove their access unless you trust them.",
    labels: ["inbox"],
    date: "Apr 22, 2022, 4:17 PM",
    attachments: ['download.png',"https://www.facebook.com/Google/"],
  },
  {
    id:2,
    subject: "Applied Finance Program | Applications Open",
    sender: "	IIM Calcutta <newsletter@vig3.cosmicjobs.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:
      "Some apps or services you allowed to access your Google Account have not been verified by Google. Since they have extensive access to your personal information, you should remove their access unless you trust them.",
    labels: [],
    date: "	Apr 23, 2022, 4:22 PM",
    attachments: ["https://docs.google.com/document/d/1fs9ldcvrq4xJpugovTD-BUERve9ukS7W7wAg2-OYd3U/edit#"],
  },
  {
    id:3,
    subject: "You might have Missed the Grand Coding Contest, but here is your chance to 𝑾𝑰𝑵!! 😎",
    sender: "	Newton School <no-reply@newtonschool.co.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:
      "Some apps or services you allowed to access your Google Account have not been verified by Google. Since they have extensive access to your personal information, you should remove their access unless you trust them.",
    labels: [],
    date: "Jan 22, 2022, 4:17 PM",
    attachments:[],
  },
  {
    id:4,
    subject: "KENT Next Gen RO Purifiers Now With Free Gift Worth Rs. 3000",
    sender: "	KENT RO Official <newsletter@vig3.cosmicjobs.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:
      "Some apps or services you allowed to access your Google Account have not been verified by Google. Since they have extensive access to your personal information, you should remove their access unless you trust them.",
    labels: [],
    date: "Feb 23, 2022, 10:43 AM",
    attachments:[],
  },
  {
    id:5,
    subject: "test",
    sender: "Avinash Malakar <avi.malakar95@gmail.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:
      "Hii,this is test user",
    labels: ["Inbox"],
    date: "Mar 2, 2022, 5:17 PM",
    attachments: ["accept.png"],
  },
  {
    id:6,
    subject: "Assignment test for React Developer Profile",
    sender: "Swarnima Shrivastava <swarnima.shrivastava@mangoitsolutions.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"As per our conversation, please find the assignment below which you need to submit it in a day.",
    labels: ["Inbox"],
    date: "Apr 22, 2022, 4:17 PM",
    attachments: ["https://docs.google.com/document/d/1fs9ldcvrq4xJpugovTD-BUERve9ukS7W7wAg2-OYd3U/edit?usp=sharing"],
  },
  {
    id:7,
    subject: "	testing",
    sender: "	muskan ved <muskan.mangoit@gmail.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"testing mail",
    labels: ["Inbox"],
    date: "May 22, 2021, 4:17 PM",
    attachments: ["java.png"],
  },
  {
    id:8,
    subject: "Mangoit, take the next step on your Linux by confirming your Google Account settings",
    sender: "The Google team <google-noreply@google.com>",
    receiver: "mangoit.mit12@gmail.com",
    content:"testing mail",
    labels: ["Inbox"],
    date: "Jun 5, 2021, 5:02 PM",
    attachments: ["https://docs.google.com/document/d/1fs9ldcvrq4xJpugovTD-BUERve9ukS7W7wAg2-OYd3U/edit?usp=sharing"],
  },
  {
    id:9,
    subject: "📚 How to use #line in C programming?",
    sender: "	InterviewBit <academy@updates.scaler.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"In C, #line is used as a preprocessor to re-set the line number in the code, which takes a parameter as line number. Here is an example for the same.",
    labels: ["Inbox"],
    date: "Apr 21, 2022, 4:39 PM",
    attachments: [],
  },
  {
    id:10,
    subject: "How’s the special day prep going? 💃😉",
    sender: "Swiggy Genie <alerts@updates.swiggy.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"Tick tasks off your to-do list Set up a task and get instant delivery of anything you need at your doorstep.   Instant needs met in a jiffy!",
    labels: ["Inbox"],
    date: "Jun 5, 2021, 5:02 PM",
    attachments: [],
  },
  {
    id:11,
    subject: "Assignment test for React Developer Profile",
    sender: "Swarnima Shrivastava <swarnima.shrivastava@mangoitsolutions.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"As per our conversation, please find the assignment below which you need to submit it in a day.",
    labels: ["Inbox"],
    date: "Apr 2, 2022, 4:17 PM",
    attachments: ["https://docs.google.com/document/d/1fs9ldcvrq4xJpugovTD-BUERve9ukS7W7wAg2-OYd3U/edit?usp=sharing"],
  },
  {
    id:12,
    subject: "React",
    sender: "Swarnima Shrivastava <swarnima.shrivastava@mangoitsolutions.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"A JavaScript library for building user interfaces",
    labels: ["Inbox"],
    date: "Jun 6, 2021, 5:02 PM",
    attachments: ["logo192.png","logo512.png"],
  },
  {
    id:13,
    subject: "Java",
    sender: "JAVA <java@gmail.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
    labels: ["Inbox"],
    date: "Apr 12, 2022, 4:17 PM",
    attachments: ["java.png"],
  },
  {
    id:14,
    subject: "Zomato - Order Food Online - Get Up To 60% Off",
    sender: "zomato <zomato@gmail.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"India's largest Food Delivery, Dining and Restaurant Discovery Service. Better food for more people.",
    labels: ["Inbox"],
    date: "Apr 03, 2022, 4:17 PM",
    attachments: ["https://www.zomato.com/sagar/restaurants?utm_source=google&utm_medium=cpc&utm_campaign=Gsearch_P-MWeb_O-NA_C-Brand_A-NewUser_SC-Generic_L-PanIndia&utm_term=zomato&gclid=CjwKCAjwx46TBhBhEiwArA_DjJD52pD_F2xEWYBe1FW757Qsa8burWeLIOsTHLiXpleZJ4vyuOy0qRoCGWcQAvD_BwE"],
  },
  {
    id:15,
    subject: "Hungry ?",
    sender: "Swiggy <swiggy@gmail.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"Order from your favorite restaurants & track on the go, with the all-new Swiggy app.",
    labels: ["Food"],
    date: "Mar 22, 2022, 2:17 PM",
    attachments: ["swiggy.png"],
  },
  {
    id:16,
    subject: "LEAKED: Wedding pictures 📸",
    sender: "Zomato <noreply@mailers.zomato.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"As per our conversation, please find the assignment below which you need to submit it in a day.",
    labels: ["Inbox"],
    date: "Dec 22, 2021, 4:17 PM",
    attachments: ["https://docs.google.com/document/d/1fs9ldcvrq4xJpugovTD-BUERve9ukS7W7wAg2-OYd3U/edit?usp=sharing"],
  },
  {
    id:17,
    subject: "Java",
    sender: "JAVA <java@gmail.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"Java is a high-level, class-based, object-oriented programming language that is designed to have as few implementation dependencies as possible.",
    labels: ["Inbox"],
    date: "Oct 22, 2021, 4:17 PM",
    attachments: ["java.png"],
  },
  {
    id:18,
    subject: "React",
    sender: "Swarnima Shrivastava <swarnima.shrivastava@mangoitsolutions.in>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"A JavaScript library for building user interfaces",
    labels: ["Inbox"],
    date: "Nov 2, 202, 4:17 PM",
    attachments: ["logo192.png"],
  },
  {
    id:19,
    subject: "📚 How to use #line in C programming?",
    sender: "	InterviewBit <academy@updates.scaler.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"In C, #line is used as a preprocessor to re-set the line number in the code, which takes a parameter as line number. Here is an example for the same.",
    labels: ["Inbox"],
    date: "May 20, 2021, 4:39 PM",
    attachments: [],
  },
  {
    id:20,
    subject: "test",
    sender: "Avinash Malakar <avi.malakar95@gmail.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:
      "Hii,this is test user",
    labels: ["Inbox"],
    date: "Jul 30, 2021, 4:17 PM",
    attachments: ["accept.png"],
  },
  {
    id:21 ,
    subject: "LEAKED: Wedding pictures 📸",
    sender: "	Zomato <noreply@mailers.zomato.com>",
    receiver: "	mangoit.mit12@gmail.com",
    content:"",
    labels: ["food"],
    date: "Aug 16, 2021, 9:17 PM",
    attachments: ["food.jpg"],
  }
  ];
